---
- name: "Add apt key"
  block:
    - name: "Download apt key"
      ansible.builtin.get_url:
        url: https://repos.influxdata.com/influxdata-archive_compat.key
        dest: /tmp/influxdata-archive_compat.key

    - name: "Install apt key"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/tmp/influxdata-archive_compat.key] https://repos.influxdata.com/debian stable main"
        state: present

- name: "Install Telegraf"
  apt:
    name: telegraf
    state: present
    update_cache: yes
