---
- name: "Add apt key"
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: "Add apt repo"
  ansible.builtin.apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: influxdb

- name: "Install Telegraf"
  ansible.builtin.apt:
    name: telegraf
    state: present
    update_cache: yes
