---

- name: "Remove default config file"
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.conf
    state: absent

- name: "Create empty default config file"
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.conf
    state: touch
    owner: root
    group: root
    mode: 0644

- name: "Remove old config dir"
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.d/
    state: absent

- name: "Create new config dir"
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.d/
    state: directory
    mode: 0755
